---
title: "Presentation Ninja"
subtitle: "Premier comité de suivi de thèse"
author: "Lilian VALLET"
institute: "Centre d'Ecologie Fonctionelle et Evolutive"
date: "2022-02-10 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["rutgers", "rutgers-fonts"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---
```{r, echo=FALSE, message=FALSE}
library(tidyverse) # Easily Install and Load the 'Tidyverse'
library(janitor) # Simple Tools for Examining and Cleaning Dirty Data
library(readxl)
library(lubridate) # Annotate Package Load Calls, [github::luisDVA/annotater] v0.1.3
library(sf) # Simple Features for R
library(tmap) # Thematic Maps
library(leaflet) # Create Interactive Web Maps with the JavaScript 'Leaflet'
library(tmaptools) # Thematic Map Tools
library(snakecase) # Convert Strings into any Case
library(ggridges)
library(pilot)
library(ggdist)
library(inspectdf)
library(ggforce)
library(mapview)
```

#Formations effectuées
- MOOC Intégrité scientifique dans les métiers de la recherche (15h, Janvier 2022)

- MOOC Rédiger et publier un article scientifique (20h, Février 2022)

- Statistiques bayésiennes avec R (12h, Avril 2022)

#Médiation scientifique
- DECLICS 2021 : 
Dialogues Entre Chercheurs et Lycéens pour les Intéresser à la Construction des Savoirs (15 Novembre 2021)
---
#Participations à des congrès nationaux
- ***GDR TheoMoDive*** : Présentation orale des travaux effectué au cours du M2 (22 - 24 Novembre 2021)

- ***Semaine de la modélisation des cultures*** (6 - 8 Décembre 2021)

#Futures participations à des congrès internationaux
- ***FirEUrisk General Meeting*** - Coimbra, Portugal : Présentation des travaux de thèse s'inscrivant dans les WP 1, 2 et 3

- ***9th International Conference on Forest Fire Research*** - Coimbra, Portugal : Présentation envisagée des travaux de thèse.


---
